swagger: "2.0"
info:
  title: NicoNihonGeemu API
  description: A REST API for managing NicoNihonGeemu decks and access dictionnary definitions
  version: 0.1.0

paths:
  /accessToken?login="{loginParam}"&pass="{passParam}":
    get:
      summary: Returns an access token to the API
      operationId: getAccessToken
      parameters:
        - login: loginParam
          in: path
          required: true
          description: Login of the user
          schema:
            type: string
        - pass: hashParam
          in: path
          required: true
          description: Hashed password of the user
          schema:
            type: string
      response:
        '200':
          description: The access token
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                  type: string
        '401':
          description: Authentication failure
  /user:
    post:
      summary: Register a new user
      operationId: registerUser
      content:
        application/json:
          schema:
            type: object
            properties:
              login:
                type: string
              pass:
                type: string
      response:
        '200':
          description: 'Registration successful'
        '409':
          description: 'Already existing user'
        '400':
          description: 'Invalid identifiers'
  /dictionnary/any/{query}:
    get:
      summary: Retrieves the definitions that match the query
      operationId: fetchDefinition
      response:
        '200': 
        summary: An array of definitions
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                $ref: '#/components/schemas/Definition'
  /dictionnary/word/{query}:
    get:
      summary: Retrieves the word definitions that match the query
      response:
        '200': 
        summary: An array of definitions
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                $ref: '#/components/schemas/Definition' 
  /dictionnary/kanji/{query}:
    get:
      summary: Retrieves the kanji meanings that match the query
      response:
        '200': 
        summary: An array of definitions
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                $ref: '#/components/schemas/Definition'


components:
  Definition:
    properties:
      name:
        type: string
      definition:
        type: string


