swagger: "2.0"
info:
  title: NicoNihonGeemu API
  description: A REST API for managing NicoNihonGeemu decks and access dictionnary definitions
  version: 0.1.0

paths:
  /accessToken?login="{loginParam}"&pass="{passParam}":
    get:
      summary: Returns an access token to the API
      operationId: getAccessToken
      tags:
        - authentication
      parameters:
        - name: loginParam
          in: path
          required: true
          summary: Login of the user
          schema:
            type: string
        - name: hashParam
          in: path
          required: true
          summary: Hashed password of the user
          schema:
            type: string
      responses:
        '200':
          description: The access token
          schema:
            type: object
            properties:
              access_token:
                type: string
        '401':
          description: Authentication failure
  /user:
    post:
      summary: Register a new user
      operationId: registerUser
      tags:
        - authentication
      schema:
        type: object
        properties:
          login:
            type: string
          pass:
            type: string
      responses:
        '200':
          description: 'Registration successful'
        '409':
          description: 'Already existing user'
        '400':
          description: 'Invalid identifiers'
  /dictionnary/any/{query}:
    get:
      summary: Retrieves the definitions that match the query
      operationId: fetchDefinition
      tags:
        - dictionnary
      responses:
        '200': 
          description: An array of definitions
  /dictionnary/word/{query}:
    get:
      summary: Retrieves the word definitions that match the query
      operationId: fetchWordDefinition
      tags:
        - dictionnary
      responses:
        '200':
          description: An array of definitions
  /dictionnary/kanji/{query}:
    get:
      summary: Retrieves the kanji meanings that match the query
      operationId: fetchKanjiDefinition
      tags:
        - dictionnary
      responses:
        '200':
          description: An array of definitions
  /deck:
    get:
      summary: Retrieves the user's decks
      operationId: fetchDecks
      tags:
        - deck
      responses:
        '200':
          description: An array of decks
    post:
      summary: Creates a new deck
      operationId: createDeck
      tags:
        - deck
      schema:
        type: object
        properties:
          name:
            type: string
      responses:
        '200':
          description: 'Deck creation successful'
        '409':
          description: 'Already existing deck'
        '400':
          description: 'Invalid name'
  /deck/{deckId}:
    get:
      summary: Retrieves the deck corresponding to the given id
      operationId: fetchDeck
      parameters:
      - in: path
        name: deckId
        type: string
        description: The id of the deck to retrieve
      tags:
        - deck
      responses:
        '200':
          description: The deck corresponding to the given id
          schema:
            $ref: '#/definitions/Deck'
        '403':
          description: Not allowed to access this deck
        '404':
          description: Deck not found
    put:
      summary: Modifies a deck's metadata
      operationId: modifyDeck
      tags:
        - deck
      parameters:
      - in: path
        name: deckId
        type: string
        description: The id of the deck to retrieve
      - in: body
        name: deckMetadata
        required: true
        schema:
          $ref: '#/definitions/DeckMetadata'
      responses:
        '200':
          description: Modifies a deck's metadata
        '403':
          description: Not allowed to access this deck
        '404':
          description: Deck not found
    delete:
      summary: Deletes the deck with the given id
      tags:
        - deck
      parameters:
      - in: path
        name: deckId
        type: string
        description: The id of the deck to retrieve
      responses:
        '200':
          description: Deck successfully deleted
        '403':
          description: Not allowed to delete this deck
        '404':
          description: Deck not found
  /deck/{deckId}/cards/:
    get:
      summary: Retrieves a deck's cards
      operationId: getDeckCards
      tags:
        - deck
      parameters:
      - in: path
        name: deckId
        description: The id of the deck
        type: string
      responses:
        '200':
          description: Returns the cards of the deck
        '403':
          description: Not allowed to access this deck
        '404':
          description: Deck not found
    post:
      summary: Adds a card to a deck
      operationId: insertCard
      tags:
        - deck
      parameters:
      - in: path
        name: deckId
        description: The id of the deck
        type: string
      - in: body
        name: card
        description: The card to add
        schema:
          $ref: '#/definitions/Card'
      responses:
        '200':
          description: Card successfully added
        '403':
          description: Not allowed to access this deck
        '404':
          description: Deck not found
  /deck/{deckId}/cards/{cardId}:
    get:
      summary: Returns the card with the given id
      operationId: getDeckCard
      tags:
        - deck
      parameters:
      - in: path
        name: deckId
        description: The id of the deck
        type: string
      - in: path
        name: cardId
        description: The id of the card
        type: string
      responses:
        '200':
          description: Returns the card
          schema:
            $ref: '#/definitions/Card'
        '403':
          description: Not allowed to access this deck
        '404':
          description: Card not found
    put:
      summary: Edit the card with the given id
      operationId: editDeckCard
      tags:
        - deck
      parameters:
      - in: path
        name: deckId
        description: The id of the deck
        type: string
      - in: path
        name: cardId
        description: The id of the card
        type: string
      - in: body
        name: card
        schema:
          $ref: '#/definitions/Card'
      responses:
        '200':
          description: Card successfully edited
        '403':
          description: Not allowed to access this deck
        '404':
          description: Card not found
    delete:
      summary: Delete the card with the given id
      operationId: deleteDeckCard
      tags:
        - deck
      parameters:
      - in: path
        name: deckId
        description: The id of the deck
        type: string
      - in: path
        name: cardId
        description: The id of the card
        type: string
      responses:
        '200':
          description: Card successfully deleted
        '403':
          description: Not allowed to access this deck
        '404':
          description: Card not found

definitions:
  Definition:
    properties:
      name:
        type: string
      definition:
        type: string
  DeckMetadata:
    properties:
      name:
        type: string
  Deck:
    properties:
      metadata:
        schema:
          $ref: '#/definitions/DeckMetadata'
      cardList:
        type: array
        items:
          $ref: '#/definitions/Card'
  Card:
    properties:
      front:
        type: string
      back:
        type: string

